name: Update

on:
  workflow_dispatch
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Beginning job..."
      - uses: actions/checkout@v2
      - run: echo "Repo has been cloned..."
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "Node setup"
      - run: yarn
      - run: echo "Dependancies installed"
      
